### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by Sneix** [wix/tpa-demo-app-jquery#5]
Followed these steps on multiple dev machines with different browsers on Windows 10:

1. Clone our starter template git clone git@github.com:wix/tpa-demo-app-jquery.git
2. Navigate to your project folder cd tpa-demo-app-react-jquery/
3. Install npm npm install
4. Run webpack webpack
5. Run the app npm start

Result: browsers give "Cannot GET /" error.

**Comment by gilatwix** [comment]
That's because there is no index.html file.

Endpoints are at widget.html & settings.html
